{{- if .Values.employeeInfo.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "self-service-agent.fullname" . }}-employee-info
  labels:
    {{- include "self-service-agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: employee-info
spec:
  replicas: {{ .Values.employeeInfo.replicaCount }}
  selector:
    matchLabels:
      {{- include "self-service-agent.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: employee-info
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "self-service-agent.labels" . | nindent 8 }}
        app.kubernetes.io/component: employee-info
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "self-service-agent.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: employee-info
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.employeeInfo.image.repository }}:{{ .Values.employeeInfo.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.employeeInfo.image.pullPolicy }}
          env:
            - name: MCP_TRANSPORT
              value: "http"
          ports:
            - name: http
              containerPort: {{ .Values.employeeInfo.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          {{- with .Values.employeeInfo.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}