{{- if .Values.employeeInfo.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "self-service-agent.fullname" . }}-employee-info
  labels:
    {{- include "self-service-agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: employee-info
spec:
  type: {{ .Values.employeeInfo.service.type }}
  ports:
    - port: {{ .Values.employeeInfo.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "self-service-agent.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: employee-info
{{- end }}